version: "3.9"
name: airoffice-env
services:
  db:
    image: postgres:14.1-alpine
    container_name: airoffice_postgres
    restart: always
    environment:
      - POSTGRES_USER=airoffice
      - POSTGRES_PASSWORD=airoffice1234
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airoffice" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local