# Generated by Django 4.1.5 on 2023-02-18 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('object', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('SEND', 'Sended'), ('START', 'Started'), ('WAIT', 'Lavoration'), ('BUSY', 'Document Wait'), ('COMP', 'Complete'), ('TRASH', 'Eliminated')], max_length=5)),
                ('status_bool', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('date_last_update', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000286CE2FA890>'), related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=250)),
                ('active_state', models.BooleanField(default=True)),
                ('img_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipe',
                'verbose_name_plural': 'Tipes',
            },
        ),
        migrations.CreateModel(
            name='TicketMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000286CE2FA890>'), related_name='client', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='ticket.ticket')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_document',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000286CE312440>'), related_name='ticket', to='ticket.tickettype'),
        ),
    ]
