# Generated by Django 4.1.5 on 2023-03-25 10:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('SEND', 'Sended'), ('START', 'Started'), ('WAIT', 'Lavoration'), ('BUSY', 'Document Wait'), ('COMP', 'Complete'), ('TRASH', 'Eliminated')], max_length=5)),
                ('status_bool', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('date_last_update', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x000001E27B328C10>'), related_name='cleint', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('img_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=60)),
                ('value', models.CharField(blank=True, max_length=60, null=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_field', to='ticket.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_type', to='ticket.tickettype'),
        ),
        migrations.CreateModel(
            name='GroupRadioButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('lable', models.CharField(max_length=60)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_radiogroup', to='ticket.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDropDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('lable', models.CharField(max_length=60)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_dropdown', to='ticket.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCeckBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('lable', models.CharField(max_length=60)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_ceckbox', to='ticket.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='FieldTextArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('lable', models.CharField(max_length=60)),
                ('placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('rows', models.IntegerField(default=6)),
                ('cols', models.IntegerField(default=40)),
                ('max_lenght', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_lenght', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_textarea', to='ticket.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='FieldInputText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('lable', models.CharField(max_length=60)),
                ('placeholder', models.CharField(blank=True, max_length=60, null=True)),
                ('value', models.CharField(blank=True, max_length=60, null=True)),
                ('max_lenght', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('min_lenght', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(249)])),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_inputtext', to='ticket.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCeckBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('lable', models.CharField(max_length=60)),
                ('default', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, max_length=60, null=True)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_field_ceckbox', to='ticket.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='ElementRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=60)),
                ('input_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_group_radiogroup', to='ticket.groupradiobutton')),
            ],
        ),
        migrations.CreateModel(
            name='ElementDropDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=60)),
                ('input_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_group_dropdown', to='ticket.groupdropdown')),
            ],
        ),
        migrations.CreateModel(
            name='ElementCeckBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=60)),
                ('input_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_group_ceckbox', to='ticket.groupceckbox')),
            ],
        ),
    ]
