# Generated by Django 4.1.5 on 2023-01-09 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_alter_ticket_cliente_alter_ticket_type_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000213FD8A9CF0>'), related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_document',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000213FD8C20E0>'), related_name='ticket', to='ticket.tickettipe'),
        ),
        migrations.AlterField(
            model_name='ticketmsg',
            name='autor',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x00000213FD8A9CF0>'), related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickettipe',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
