# Generated by Django 4.1.5 on 2023-01-31 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0009_alter_ticket_cliente_alter_ticket_type_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x0000025FDD0FA890>'), related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_document',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x0000025FDD112530>'), related_name='ticket', to='ticket.tickettipe'),
        ),
        migrations.AlterField(
            model_name='ticketmsg',
            name='autor',
            field=models.ForeignKey(on_delete=models.SET('<django.db.models.query_utils.DeferredAttribute object at 0x0000025FDD0FA890>'), related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
