# Generated by Django 4.1.5 on 2023-03-25 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('FREE', 'Available'), ('WAIT', 'Wait'), ('BLOCK', 'Booked')], max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('type', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('FREE', 'Available'), ('WAIT', 'Wait'), ('BUSY', 'Booked'), ('BLOCK', 'Blocked'), ('PAUSE', 'Suspended')], max_length=5)),
                ('available', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('prenotation_time', models.DateTimeField(auto_now_add=True)),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.appointments')),
                ('commiter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
