# Generated by Django 4.1.5 on 2023-01-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_prebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prebooking',
            old_name='creatore',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='booking',
            name='stato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='tato',
            field=models.BooleanField(default=False),
        ),
    ]
