# Generated by Django 4.1.5 on 2023-01-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_creatore_prebooking_owner_booking_stato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tato',
        ),
        migrations.AddField(
            model_name='booking',
            name='abilitato',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='stato',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stato',
            field=models.IntegerField(),
        ),
    ]
