# Generated by Django 4.1.5 on 2023-01-06 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_remove_booking_tato_booking_abilitato_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreBooking',
            new_name='Appointments',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='prebooking',
        ),
        migrations.AddField(
            model_name='booking',
            name='appointments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.appointments'),
        ),
    ]
