# Generated by Django 4.1.5 on 2023-01-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_prebooking_appointments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.appointments'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stato',
            field=models.CharField(choices=[('FREE', 'Available'), ('BUSY', 'Busy'), ('WAIT', 'Wait'), ('BLOCK', 'Booked')], max_length=5),
        ),
    ]
