# Generated by Django 4.1.5 on 2023-01-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_appointments_alter_booking_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stato',
            field=models.CharField(choices=[('FREE', 'Available'), ('WAIT', 'Wait'), ('BUSY', 'Busy'), ('BLOCK', 'Booked'), ('PAUSE', 'Suspended')], max_length=5),
        ),
    ]
