# Generated by Django 4.1.5 on 2023-01-07 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prenotation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
