# Generated by Django 4.1.5 on 2023-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_prenotation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='stato',
            field=models.CharField(choices=[('FREE', 'Available'), ('WAIT', 'Wait'), ('BLOCK', 'Booked')], max_length=5),
        ),
    ]
