# Generated by Django 4.1.5 on 2023-01-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_appointments_active_alter_appointments_stato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='stato',
            new_name='state',
        ),
    ]
