# Generated by Django 4.1.5 on 2023-01-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_rename_active_appointments_stato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='stato',
            new_name='active',
        ),
    ]
