# Generated by Django 4.1.5 on 2023-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_rename_stato_appointments_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stato',
            field=models.CharField(choices=[('FREE', 'Available'), ('WAIT', 'Wait'), ('BUSY', 'Booked'), ('BLOCK', 'Blocked'), ('PAUSE', 'Suspended')], max_length=5),
        ),
    ]
